name: Test KubeRay Operator Upgrade to latest available helm image

on:
  # pull_request:
  #   branches:
  #     - '**'
  # push:
  #   branches:
  #     - dev
  #     - 'release-*'
  # workflow_dispatch: # to allow running on demand
  repository_dispatch:
    types: [branch-dispatch]

jobs:
  run_kuberay_upgrade_tests:
    # runs-on: ubuntu-22.04
    runs-on: kuberay-test
    # runs-on: kuberay-8-32
    permissions:
      contents: read
    steps:
    #   - name: Get System Information
    #     id: system-info
    #     uses: kenchan0130/actions-system-info@master
    #   - name: Print CPU and RAM
    #     run: |
    #       echo "CPU Cores: ${{ steps.system-info.outputs.cpu-core }}"
    #       echo "Total Memory: ${{ steps.system-info.outputs.totalmem }}"
      - name: Checkout kuberay Repository
        uses: actions/checkout@v4
        with:
          repository: pawelpaszki/kuberay
          # fetch-depth: 0
          ref: ${{ github.event.client_payload.branch }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.24'

      - name: Install go dependencies
        run: |
          cd ${{ github.workspace }}/ray-operator
          go mod download
      - name: Install helm
        run: |
          curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.12.2-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm repo add kuberay https://ray-project.github.io/kuberay-helm/
          helm repo update
      # - name: Install kind
      #   run: |
      #     curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
      #     chmod +x ./kind
      #     mv ./kind /usr/local/bin/kind

      # - name: Create Kind Cluster
      #   run: kind create cluster #--image=kindest/node:v1.25.0@sha256:428aaa17ec82ccde0131cb2d1ca6547d13cf5fdabcc0bbecf749baa935387cbf

      - name: Setup and start KinD cluster
        run:
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind

      - name: Set kubectl context
        run: kubectl cluster-info --context kind-kind

      # - name: Describe nodes
      #   run: kubectl describe nodes

      # - name: wait for nodes ready
      #   run: |
      #     for node in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}'); do
      #       kubectl wait --for=condition=Ready "node/$node" --timeout=300s
      #     done
      - name: Install Older KubeRay Operator (v1.3.2)
        run: |
          helm repo add kuberay https://ray-project.github.io/kuberay-helm/
          helm install kuberay-operator kuberay/kuberay-operator --version 1.3.2
      - name: Wait for Kuberay Operator to be available
        run: kubectl wait --timeout=90s --for=condition=Available=true deployment -n default kuberay-operator

      - name: Prepare and Run Upgrade Tests
        run: |
          cd ray-operator
          echo "--- START:Running e2e Operator upgrade (v1.3.2 to v1.4.0 operator) tests"
          KUBERAY_TEST_TIMEOUT_SHORT=1m KUBERAY_TEST_TIMEOUT_MEDIUM=5m KUBERAY_TEST_TIMEOUT_LONG=10m KUBERAY_TEST_UPGRADE_IMAGE=v1.4.0 \
          go test -timeout 30m -v ./test/e2eupgrade
          echo "--- END:e2e Operator upgrade (v1.3.2 to v1.4.0 operator) tests finished"
      # - name: Check runner disk usage
      #   if: always()
      #   run: |
      #     echo "Disk Usage of GitHub Runner:"
      #     df -h
      - name: Debug Kubernetes Cluster on Failure
        if: failure()
        run: |
          echo "--- DEBUG OUTPUT ---"
          echo "Checking GitHub Runner resources..."
          lscpu
          free -h
          echo "Checking Kubernetes cluster state..."
          kubectl cluster-info
          kubectl get nodes
          
          echo "Describing all nodes..."
          kubectl describe nodes
          echo "Printing all Kubernetes events..."
          kubectl get events --all-namespaces
          echo "Getting logs of Kind control plane container..."
          docker logs kind-control-plane
          echo "--- END OF DEBUG OUTPUT ---"
      - name: Display all pods on kind cluster
        if: failure()
        run: kubectl get pods -A

      - name: Cleanup
        if: always()
        run: kind delete clusters --all || true
